// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoexample/example.proto

package protoexample

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Foo struct {
	Bar                  string   `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	Baz                  string   `protobuf:"bytes,2,opt,name=baz,proto3" json:"baz,omitempty"`
	Extension            *any.Any `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa9743ae572dcf9, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func (m *Foo) GetBaz() string {
	if m != nil {
		return m.Baz
	}
	return ""
}

func (m *Foo) GetExtension() *any.Any {
	if m != nil {
		return m.Extension
	}
	return nil
}

func init() {
	proto.RegisterType((*Foo)(nil), "openmatchecosystem.protoexample.Foo")
}

func init() { proto.RegisterFile("protoexample/example.proto", fileDescriptor_0fa9743ae572dcf9) }

var fileDescriptor_0fa9743ae572dcf9 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x87, 0xd2, 0x7a, 0x60, 0x41, 0x21, 0xf9,
	0xfc, 0x82, 0xd4, 0xbc, 0xdc, 0xc4, 0x92, 0xe4, 0x8c, 0xd4, 0xe4, 0xfc, 0xe2, 0xca, 0xe2, 0x92,
	0xd4, 0x5c, 0x3d, 0x64, 0xe5, 0x52, 0x92, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0xc1,
	0xa4, 0xd2, 0x34, 0xfd, 0xc4, 0xbc, 0x4a, 0x88, 0x0a, 0xa5, 0x58, 0x2e, 0x66, 0xb7, 0xfc, 0x7c,
	0x21, 0x01, 0x2e, 0xe6, 0xa4, 0xc4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x13,
	0x22, 0x52, 0x25, 0xc1, 0x04, 0x13, 0xa9, 0x12, 0x32, 0xe2, 0xe2, 0x4c, 0xad, 0x28, 0x49, 0xcd,
	0x2b, 0xce, 0xcc, 0xcf, 0x93, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd1, 0x83, 0x98, 0xac,
	0x07, 0x33, 0x59, 0xcf, 0x31, 0xaf, 0x32, 0x08, 0xa1, 0xcc, 0x28, 0x9e, 0x8b, 0x25, 0x24, 0xb5,
	0xb8, 0x44, 0x28, 0x9c, 0x8b, 0xd3, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0x64, 0x99, 0x8a, 0x1e,
	0x01, 0x07, 0xeb, 0xb9, 0xe5, 0xe7, 0x4b, 0x11, 0xa5, 0xca, 0xc9, 0x28, 0xca, 0x00, 0xa4, 0x4c,
	0x17, 0xac, 0x4e, 0x2f, 0x25, 0xb5, 0x4c, 0x1f, 0xc1, 0xd5, 0x85, 0xeb, 0xd3, 0x47, 0xd6, 0x97,
	0xc4, 0x06, 0xe6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x90, 0xf8, 0xd1, 0x54, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	CreateFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) CreateFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/openmatchecosystem.protoexample.Test/CreateFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	CreateFoo(context.Context, *Foo) (*Foo, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) CreateFoo(ctx context.Context, req *Foo) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFoo not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_CreateFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).CreateFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmatchecosystem.protoexample.Test/CreateFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).CreateFoo(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openmatchecosystem.protoexample.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFoo",
			Handler:    _Test_CreateFoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoexample/example.proto",
}
