apiVersion: apps/v1
kind: Deployment
metadata:
  name: soloduel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soloduel
  template:
    metadata:
      labels:
        app: soloduel
    spec:
      containers:
      - name: soloduel
        image: us-docker.pkg.dev/open-match-public-images/open-match2/soloduel
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: soloduel-service
spec:
  selector:
    app: soloduel
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP