// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defaultevaluator/messages.proto

package defaultevaluator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A DefaultEvaluationCriteria is used for a match's evaluation_input when using
// the default evaluator.
type DefaultEvaluationCriteria struct {
	Score                float64  `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultEvaluationCriteria) Reset()         { *m = DefaultEvaluationCriteria{} }
func (m *DefaultEvaluationCriteria) String() string { return proto.CompactTextString(m) }
func (*DefaultEvaluationCriteria) ProtoMessage()    {}
func (*DefaultEvaluationCriteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_37e44edbfbec1774, []int{0}
}

func (m *DefaultEvaluationCriteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultEvaluationCriteria.Unmarshal(m, b)
}
func (m *DefaultEvaluationCriteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultEvaluationCriteria.Marshal(b, m, deterministic)
}
func (m *DefaultEvaluationCriteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultEvaluationCriteria.Merge(m, src)
}
func (m *DefaultEvaluationCriteria) XXX_Size() int {
	return xxx_messageInfo_DefaultEvaluationCriteria.Size(m)
}
func (m *DefaultEvaluationCriteria) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultEvaluationCriteria.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultEvaluationCriteria proto.InternalMessageInfo

func (m *DefaultEvaluationCriteria) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*DefaultEvaluationCriteria)(nil), "openmatchecosystem.default_evaluator.DefaultEvaluationCriteria")
}

func init() { proto.RegisterFile("defaultevaluator/messages.proto", fileDescriptor_37e44edbfbec1774) }

var fileDescriptor_37e44edbfbec1774 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x49, 0x4d, 0x4b,
	0x2c, 0xcd, 0x29, 0x49, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x2c, 0xc9, 0x2f, 0xd2, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xc9, 0x2f, 0x48,
	0xcd, 0xcb, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0x4d, 0xce, 0x2f, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5,
	0x83, 0xea, 0x89, 0x87, 0x6b, 0x52, 0x32, 0xe4, 0x92, 0x74, 0x81, 0x08, 0xba, 0x42, 0xc4, 0x32,
	0xf3, 0xf3, 0x9c, 0x8b, 0x32, 0x4b, 0x52, 0x8b, 0x32, 0x13, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x93,
	0xf3, 0x8b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0x20, 0x1c, 0x27, 0xa7, 0x28, 0x13,
	0x90, 0xd1, 0xba, 0x60, 0xb3, 0xf5, 0x52, 0x52, 0xcb, 0xf4, 0x11, 0x5c, 0x5d, 0xb8, 0x5d, 0xfa,
	0xe8, 0xee, 0x5b, 0xc5, 0xc4, 0xe9, 0x5f, 0x90, 0x9a, 0xe7, 0x0b, 0x52, 0x96, 0xc4, 0x06, 0x76,
	0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x89, 0x78, 0x9b, 0x3f, 0xc6, 0x00, 0x00, 0x00,
}
